### ISSUE TITLE
rig project doctor

### ISSUE THREAD

**Issue by grayside** [phase2/rig#58]
Should we have a rig project doctor?

I've gone back and forth on this a bit: Should it be a generated script? Should it be in rig? A separate tool? Extensible? Runnable from Jenkins? Lots of questions.

With this functionality, we may be able to automate checks for a lot more of the problems projects run into and fasttrack diagnoses.

Here's the specification of what I had in mind:

```yaml
doctor:
  conditions:
    -
      name: Valid Docker Compose Configuration
      diagnosis: Your docker-compose files do not provide a valid configuration.
      prescription: Evaluate the errors and revise the configuration files as needed.
      # If a check fails on a fatal severity issue, stop the process.
      severity: error
      check:
        - validate-docker-compose.sh
    -
      name: Scaffolded Files Exist
      diagnosis: Some of the generated files for your project have gone missing. This can lead to unpredictable results.
      prescription: Replace missing files from git history or a rerun of the generator. If any file is not needed, please delete from this check.
     severity: warning
     # Checks should be run sequentially and the whole step failed if any one fails.
     check:
       - ls src > /dev/null
       - ls package.json > /dev/null
```

### Unison Sync Crash

* Diagnosis: Your unison sync crashed and will not work without further action.
* Prescription: Stop your project containers, run `docker container rm -f projectname-sync` and `docker volume rm -f projectname-sync`
* Severity: Fatal

### Containers Down

* Diagnosis: No containers associated with the projectname are currently operating.
* Prescription: Start your project containers before relying on their services.
* Severity: Warning
